import type { BroadcastTheme } from "@/types/broadcast"

const baseTheme: Omit<BroadcastTheme, "id" | "name" | "background" | "verseText" | "reference" | "layout" | "transition" | "textBox"> = {
  builtin: true,
  pinned: false,
  createdAt: 0,
  updatedAt: 0,
  resolution: { width: 1920, height: 1080 },
  divider: {
    style: "none" as const,
    color: "#ffffff",
    width: 40,
    opacity: 0.5,
    dotCount: 4,
    dotSize: 4,
  },
  verseNumbers: {
    visible: true,
    fontSize: 14,
    color: "#ffffff",
    superscript: true,
  },
}

const CLASSIC_DARK: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-classic-dark",
  name: "Classic Dark",
  background: {
    type: "gradient",
    color: "#1a1a3e",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#1a1a3e", position: 0 },
        { color: "#0a0a1a", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Source Serif 4 Variable",
    fontSize: 72,
    fontWeight: 400,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: null,
    outline: null,
    lineBreakMode: "flow" as const,
  },
  verseNumbers: {
    visible: true,
    fontSize: 20,
    color: "#d4a574",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 48,
    fontWeight: 500,
    color: "#d4a574",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 2,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 80, bottom: 60, left: 80 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 80,
    referenceGap: 32,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const MODERN_LIGHT: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-modern-light",
  name: "Modern Light",
  background: {
    type: "solid",
    color: "#f5f5f0",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 68,
    fontWeight: 400,
    color: "#1a1a1a",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.6,
    letterSpacing: 0,
    shadow: null,
    outline: null,
    lineBreakMode: "flow" as const,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#666666",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 45,
    fontWeight: 500,
    color: "#666666",
    horizontalAlign: "left",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 0,
    position: "above",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 60, right: 80, bottom: 60, left: 80 },
    textAlign: "left",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 80,
    textAreaHeight: 80,
    referenceGap: 30,
  },
  transition: {
    type: "slide",
    duration: 400,
    easing: "ease-out",
    direction: "up",
  },
}

const BROADCAST_OVERLAY: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-broadcast-overlay",
  name: "Broadcast Overlay",
  background: {
    type: "transparent",
    color: "transparent",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: true,
    color: "#000000",
    opacity: 0.7,
    borderRadius: 12,
    padding: 24,
  },
  verseText: {
    fontFamily: "Geist Variable",
    fontSize: 64,
    fontWeight: 500,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.5,
    letterSpacing: 0,
    shadow: { color: "rgba(0,0,0,0.8)", blur: 8, x: 0, y: 2 },
    outline: null,
    lineBreakMode: "flow" as const,
  },
  verseNumbers: {
    visible: true,
    fontSize: 18,
    color: "#fbbf24",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 43,
    fontWeight: 600,
    color: "#fbbf24",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    uppercase: false,
    letterSpacing: 1,
    position: "below",
  },
  layout: {
    anchor: "bottom-center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 40, right: 60, bottom: 40, left: 60 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 90,
    textAreaHeight: 40,
    referenceGap: 24,
  },
  transition: {
    type: "fade",
    duration: 300,
    easing: "ease-in-out",
    direction: "up",
  },
}

const WARM_WORSHIP: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-warm-worship",
  name: "Warm Worship",
  background: {
    type: "gradient",
    color: "#e8451c",
    gradient: {
      type: "linear",
      angle: 135,
      stops: [
        { color: "#e8451c", position: 0 },
        { color: "#d4652e", position: 25 },
        { color: "#9b4dca", position: 70 },
        { color: "#6a3fa0", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Inter Variable",
    fontSize: 60,
    fontWeight: 600,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    lineHeight: 1.9,
    letterSpacing: 3,
    shadow: { color: "rgba(0,0,0,0.3)", blur: 8, x: 0, y: 2 },
    outline: null,
    lineBreakMode: "centered-lines" as const,
  },
  divider: {
    style: "line" as const,
    color: "#ffffff",
    width: 40,
    opacity: 0.5,
    dotCount: 4,
    dotSize: 4,
  },
  reference: {
    fontFamily: "Inter Variable",
    fontSize: 36,
    fontWeight: 500,
    color: "rgba(255,255,255,0.8)",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 4,
    position: "below",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 100, bottom: 80, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 75,
    textAreaHeight: 80,
    referenceGap: 40,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const PURE_MINIMAL: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-pure-minimal",
  name: "Pure Minimal",
  background: {
    type: "solid",
    color: "#000000",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Inter Variable",
    fontSize: 56,
    fontWeight: 400,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    lineHeight: 2.2,
    letterSpacing: 3,
    shadow: null,
    outline: null,
    lineBreakMode: "centered-lines" as const,
  },
  divider: {
    style: "dots" as const,
    color: "#ffffff",
    width: 40,
    opacity: 1.0,
    dotCount: 4,
    dotSize: 4,
  },
  reference: {
    fontFamily: "Inter Variable",
    fontSize: 32,
    fontWeight: 400,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 5,
    position: "below",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 100, right: 120, bottom: 100, left: 120 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 60,
    textAreaHeight: 70,
    referenceGap: 60,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const WARM_DARK: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-warm-dark",
  name: "Warm Dark",
  background: {
    type: "gradient",
    color: "#2d1b00",
    gradient: {
      type: "linear",
      angle: 180,
      stops: [
        { color: "#2d1b00", position: 0 },
        { color: "#1a0f00", position: 40 },
        { color: "#0a0500", position: 100 },
      ],
    },
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Source Serif 4 Variable",
    fontSize: 64,
    fontWeight: 400,
    color: "#e8d5b5",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.8,
    letterSpacing: 0,
    shadow: null,
    outline: null,
    lineBreakMode: "flow" as const,
  },
  divider: {
    style: "line" as const,
    color: "#d4a574",
    width: 40,
    opacity: 0.4,
    dotCount: 4,
    dotSize: 4,
  },
  reference: {
    fontFamily: "Inter Variable",
    fontSize: 36,
    fontWeight: 500,
    color: "#d4a574",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 3,
    position: "below",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 80, right: 100, bottom: 80, left: 100 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 70,
    textAreaHeight: 80,
    referenceGap: 40,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const PURE_MINIMAL_LIGHT: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-pure-minimal-light",
  name: "Pure Minimal (Light)",
  background: {
    type: "solid",
    color: "#fafaf8",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Inter Variable",
    fontSize: 56,
    fontWeight: 400,
    color: "#1a1a1a",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    lineHeight: 2.2,
    letterSpacing: 3,
    shadow: null,
    outline: null,
    lineBreakMode: "centered-lines" as const,
  },
  divider: {
    style: "dots" as const,
    color: "#1a1a1a",
    width: 40,
    opacity: 1.0,
    dotCount: 4,
    dotSize: 4,
  },
  reference: {
    fontFamily: "Inter Variable",
    fontSize: 32,
    fontWeight: 400,
    color: "#1a1a1a",
    horizontalAlign: "center",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 5,
    position: "below",
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 100, right: 120, bottom: 100, left: 120 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 60,
    textAreaHeight: 70,
    referenceGap: 60,
  },
  transition: {
    type: "fade",
    duration: 500,
    easing: "ease-in-out",
    direction: "up",
  },
}

const BOLD_PROCLAMATION: BroadcastTheme = {
  ...baseTheme,
  id: "builtin-bold-proclamation",
  name: "Bold Proclamation",
  background: {
    type: "solid",
    color: "#000000",
    gradient: null,
    image: null,
  },
  textBox: {
    enabled: false,
    color: "#000000",
    opacity: 0,
    borderRadius: 0,
    padding: 0,
  },
  verseText: {
    fontFamily: "Inter Variable",
    fontSize: 104,
    fontWeight: 600,
    color: "#ffffff",
    horizontalAlign: "center",
    verticalAlign: "middle",
    textTransform: "none",
    textDecoration: "none",
    lineHeight: 1.4,
    letterSpacing: 0.5,
    shadow: { color: "rgba(0,0,0,0.6)", blur: 16, x: 0, y: 4 },
    outline: null,
    lineBreakMode: "flow" as const,
    autoFit: true,
    minFontSize: 40,
  },
  verseNumbers: {
    visible: false,
    fontSize: 28,
    color: "#fbbf24",
    superscript: true,
  },
  reference: {
    fontFamily: "Geist Variable",
    fontSize: 56,
    fontWeight: 700,
    color: "#fbbf24",
    horizontalAlign: "right",
    verticalAlign: "top",
    textTransform: "uppercase",
    textDecoration: "none",
    uppercase: true,
    letterSpacing: 8,
    position: "above",
    standalone: {
      anchor: "bottom-right",
      margin: 60,
    },
  },
  divider: {
    style: "line" as const,
    color: "#fbbf24",
    width: 80,
    opacity: 0.8,
    dotCount: 4,
    dotSize: 4,
  },
  layout: {
    anchor: "center",
    offsetX: 0,
    offsetY: 0,
    padding: { top: 40, right: 60, bottom: 40, left: 60 },
    textAlign: "center",
    backgroundWidth: 100,
    backgroundHeight: 100,
    textAreaWidth: 94,
    textAreaHeight: 96,
    referenceGap: 56,
  },
  logo: {
    url: "/EWC-White.png",
    position: "top-left",
    size: 120,
    opacity: 1,
    margin: 48,
  },
  transition: {
    type: "fade",
    duration: 400,
    easing: "ease-in-out",
    direction: "up",
  },
}

const BOLD_CRIMSON: BroadcastTheme = {
  ...BOLD_PROCLAMATION,
  id: "builtin-bold-crimson",
  name: "Bold Crimson",
  background: {
    type: "gradient",
    color: "#160708",
    gradient: {
      type: "linear",
      angle: 145,
      stops: [
        { color: "#160708", position: 0 },
        { color: "#5b1016", position: 58 },
        { color: "#d4a15f", position: 100 },
      ],
    },
    image: null,
  },
  verseText: {
    ...BOLD_PROCLAMATION.verseText,
    color: "#fff8ee",
    shadow: { color: "rgba(0,0,0,0.72)", blur: 18, x: 0, y: 5 },
  },
  verseNumbers: {
    ...BOLD_PROCLAMATION.verseNumbers,
    color: "#f8c978",
  },
  reference: {
    ...BOLD_PROCLAMATION.reference,
    color: "#f8c978",
  },
  divider: {
    ...BOLD_PROCLAMATION.divider,
    color: "#f8c978",
  },
}

const BOLD_COBALT: BroadcastTheme = {
  ...BOLD_PROCLAMATION,
  id: "builtin-bold-cobalt",
  name: "Bold Cobalt",
  background: {
    type: "gradient",
    color: "#06121f",
    gradient: {
      type: "radial",
      angle: 0,
      stops: [
        { color: "#163a66", position: 0 },
        { color: "#06121f", position: 72 },
        { color: "#02050a", position: 100 },
      ],
    },
    image: null,
  },
  verseText: {
    ...BOLD_PROCLAMATION.verseText,
    color: "#f4fbff",
    shadow: { color: "rgba(0,0,0,0.75)", blur: 20, x: 0, y: 5 },
  },
  verseNumbers: {
    ...BOLD_PROCLAMATION.verseNumbers,
    color: "#8fd8ff",
  },
  reference: {
    ...BOLD_PROCLAMATION.reference,
    color: "#8fd8ff",
  },
  divider: {
    ...BOLD_PROCLAMATION.divider,
    color: "#8fd8ff",
  },
  logo: {
    ...BOLD_PROCLAMATION.logo!,
    opacity: 0.9,
  },
}

const BOLD_CHAPEL: BroadcastTheme = {
  ...BOLD_PROCLAMATION,
  id: "builtin-bold-chapel",
  name: "Bold Chapel",
  background: {
    type: "solid",
    color: "#f8f5ef",
    gradient: null,
    image: null,
  },
  verseText: {
    ...BOLD_PROCLAMATION.verseText,
    color: "#171717",
    fontWeight: 700,
    shadow: null,
  },
  verseNumbers: {
    ...BOLD_PROCLAMATION.verseNumbers,
    color: "#8a5a20",
  },
  reference: {
    ...BOLD_PROCLAMATION.reference,
    color: "#8a5a20",
  },
  divider: {
    ...BOLD_PROCLAMATION.divider,
    color: "#8a5a20",
  },
  logo: {
    ...BOLD_PROCLAMATION.logo!,
    url: "/manna-logo.png",
    opacity: 0.9,
  },
}

export const BUILTIN_THEMES: BroadcastTheme[] = [
  BOLD_PROCLAMATION,
  BOLD_CRIMSON,
  BOLD_COBALT,
  BOLD_CHAPEL,
]
