[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

Format based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project loosely follows [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
body = """
{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif %}
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group | upper_first }}

{% for commit in commits -%}
- {{ commit.message | upper_first | trim }}{% if commit.scope %} _({{ commit.scope }})_{% endif %}
{% endfor %}
{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^refactor", group = "Changed" },
  { message = "^perf", group = "Performance" },
  { message = "^polish", group = "Changed" },
  { message = "^docs", group = "Documentation" },
  { message = "^test", group = "Tests" },
  { message = "^chore", group = "Maintenance" },
  { message = "^style", skip = true },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
